/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LanguageStringUtils */

#ifndef _Included_LanguageStringUtils
#define _Included_LanguageStringUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LanguageStringUtils
 * Method:    length
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_Language_LanguageStringUtils_length
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
