/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LanguageStringUtils */

#ifndef _Included_LanguageStringUtils
#define _Included_LanguageStringUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LanguageStringUtils
 * Method:    length
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_Language_LanguageStringUtils_length
  (JNIEnv *, jobject, jstring, jint);


/*
 * Class:     LanguageStringUtils
 * Method:    lengthEscaped
 * Signature: (Ljava/lang/String;I;java/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_Language_LanguageStringUtils_lengthEscaped
  (JNIEnv *, jobject, jstring, jint, jstring, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    lengthEscapedEnd
 * Signature: (Ljava/lang/String;I;java/lang/String;I;java/lang/String)I
 */
JNIEXPORT jint JNICALL Java_com_Language_LanguageStringUtils_lengthEscapedWithEnd
  (JNIEnv *, jobject, jstring, jint, jstring, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isNaturalNumber
 * Signature: (Ljava/lang/String;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isNaturalNumber
(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isHexNumber
 * Signature: (Ljava/lang/String;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isHexNumber
(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isValid
 * Signature: (Ljava/lang/String;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isValid
(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isInRomanceAlphabet
 * Signature: (Ljava/lang/String;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isInRomanceAlphabet
(JNIEnv *, jobject, jstring, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isInAlphabet
 * Signature: (Ljava/lang/String;I;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isInAlphabet
(JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isInUpperCaseInAlphabet
 * Signature: (Ljava/lang/String;I;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isInUpperCaseInAlphabet
(JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isLowerCaseInAlphabet
 * Signature: (Ljava/lang/String;I;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isLowerCaseInAlphabet
(JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     LanguageStringUtils
 * Method:    isLowerCaseInAlphabet
 * Signature: (Ljava/lang/String;I;I)B
 */
JNIEXPORT jboolean JNICALL Java_com_Language_LanguageStringUtils_isPunctucationMarkInAlphabet
(JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
